name: acies
description: duel calculator
version: 1.0.0

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  equatable: ^1.0.1
  flutter_bloc: ^2.0.1
  dartz: ^0.8.9
  shared_preferences: ^0.5.4+6
  flushbar: ^1.9.1
  flutter_native_splash: ^0.1.9
  flutter_launcher_icons: ^0.7.4
  firebase_admob: ^0.9.0+9
  firebase_core: ^0.4.2
  firebase_analytics: ^5.0.6

flutter_native_splash:
  image: assets/splash/acies.png
  color: "212327"

flutter_icons:
  image_path: "assets/launcher.png"
  android: "acies_launcher"

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/dice/
    - assets/coins/
    - assets/scroll/
    - assets/splash/
