name: acies
description: duel calculator
version: 1.0.0

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  equatable: ^1.0.1
  flutter_bloc: ^2.1.1
  dartz: ^0.8.9
  shared_preferences: ^0.5.6
  flushbar: ^1.9.1
  flutter_launcher_icons: ^0.7.4
  firebase_admob: ^0.9.0+10
  firebase_core: ^0.4.3+1
  firebase_analytics: ^5.0.9
  keyboard_avoider: ^0.1.2
  path_provider: ^1.5.1
  uuid: 2.0.4

flutter_icons:
  image_path: "assets/launcher.png"
  android: "acies_launcher"

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1
  effective_dart: ^1.1.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/dice/
    - assets/coins/
    - assets/scroll/
