import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';

import '../../blocs/blocs.dart';
import '../snack_bars.dart';

/// Reset button widget.
class ResetButton extends StatelessWidget {
  /// [iconSize] is generated by parent.
  final double iconSize;

  /// Constructor
  ResetButton(this.iconSize);

  @override
  Widget build(BuildContext context) {
    return InkWell(
      onTap: () {
        onTapReset(context);
        BlocProvider.of<SwipeBarBloc>(context).add(SwipeBarResetEvent());
      },
      child: Image(
        image: AssetImage('assets/reset.png'),
        width: iconSize,
      ),
    );
  }
}

/// Reset function used by all reset widgets.
void onTapReset(BuildContext context) {
  BlocProvider.of<NotesBloc>(context).add(NotesMatchOverEvent());
  BlocProvider.of<TopBarBloc>(context).add(TopBarResetEvent());
  BlocProvider.of<CalculatorBloc>(context).add(CalculatorResetEvent());
  BlocProvider.of<TimerBloc>(context).add(TimerResetEvent(matchReset: true));
  BlocProvider.of<HistoryBloc>(context).add(HistoryResetEvent());
  BlocProvider.of<NotesBloc>(context).add(NotesResetEvent());
  noTitleSnackBar(context, 'Match reset');
}
