import 'package:flutter/material.dart';

import '../../utils/constants.dart';
import '../route_builder.dart';

/// Notes icon for game list items.
class Notes extends StatelessWidget {
  /// [iconSize] is generated by parent.
  final double iconSize;

  /// [notes] Map contains all notes for this game.
  final Map<String, dynamic> notes;

  /// Constructor
  Notes(this.iconSize, this.notes);

  @override
  Widget build(BuildContext context) {
    return InkWell(
      onTap: () => Navigator.of(context).push(sizedRouteBuilder(
          context, notesWidget(context, notes), .7, .8, primaryColor)),
      child: Icon(
        Icons.create,
        size: iconSize,
      ),
    );
  }
}

/// When Notes icon is tapped this widget is pushed onto the screen, displaying all the notes.
/// players took during this game.
Widget notesWidget(BuildContext context, Map<String, dynamic> notes) {
  var textStyle = TextStyle(fontSize: MediaQuery.of(context).size.width / 22);
  return Material(
    type: MaterialType.transparency,
    child: Column(
      children: <Widget>[
        Padding(
          padding: const EdgeInsets.only(left: 10.0, right: 10.0, top: 10.0),
          child: Text(
            notes.keys.first == '' ? 'No Title' : notes.keys.first,
            textAlign: TextAlign.center,
            style: textStyle,
          ),
        ),
        Expanded(
          child: SingleChildScrollView(
            child: Padding(
              padding: const EdgeInsets.all(10.0),
              child: Container(
                width: MediaQuery.of(context).size.width * .8,
                child: Text(
                  notes.values.first == '' ? 'No Notes' : notes.values.first,
                  style: textStyle,
                ),
              ),
            ),
          ),
        ),
      ],
    ),
  );
}
